# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Community
    url: community/
    weight: 50
  - name: Index
    url: /index
    weight: 50 
    # Adjust weight to position it left/right


