hugoblox:
  schema: "2.0"
  identity:
    name: Master Dark-Net
    type: organization
    tagline: Master Dark-Net
    description: An Awesome List of Materials to Master the Art of Dark-web and Deep-web. The Most Comprehensive and Deepest guide ever made for Hidden Services.
    organization: yottajunaid
  theme:
    mode: system
    pack: dracula
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: native
    size: md
  layout:
    radius: none
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  #footer:
    #style: minimal
    #language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
#  search:
#    enable: true
#    provider: fuse
  features:
    search:
      provider: fuse
      config:
        shouldSort: true
        threshold: 0.5  # Lower = more exact matching
        location: 0
        distance: 100
        maxPatternLength: 32
        minMatchCharLength: 2
        keys:
          - name: "title"
            weight: 0.8
          - name: "summary"
            weight: 0.5
          - name: "content"
            weight: 0.3 
  diagram: true
  marketing:
    analytics:
      google_analytics: 'G-CG24V4GJEC'
